// Generated by ts-to-zod
import { z } from "zod";

export const createChapitreInputSchema = z.object({
  name: z.string().min(1, { message: "Name is required" }), // Custom error message for name
  description: z.string().optional(), // Optional field
  matiereId: z.string().min(1, { message: "Matiere ID is required" }), // Custom error message for matiereId
  isLocked: z.boolean().optional(), // Optional field
  estTermine: z.boolean({
    required_error: "Completion status is required", // Custom error message for estTermine
  }),
});

export const getChapitreByIdSchema = z.object({
  id: z.string(),
});

export const deleteChapitreByIdSchema = z.object({
  id: z.string(),
});

export const updateChapitreByIdSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  description: z.string().optional(),
  matiereId: z.string(),
  isLocked: z.boolean().optional(),
});

export const getAllChapitersByMatiersSchema = z.object({
  matiers: z.union([z.string(), z.array(z.string())]),
});
