// Generated by ts-to-zod
import { z } from "zod";

export const createCourInputSchema = z.object({
  name: z.string().min(1, { message: "Name is required" }),
  images: z
    .array(z.string())
    .min(1, { message: "At least one image is required" }),
  content: z.string().min(1, { message: "Content is required" }),
  chapitreId: z.string().min(1, { message: "Chapter ID is required" }),
  isLocked: z.boolean().optional(),
  description: z.string().optional(),
});

export const getCourByIdSchema = z.object({
  id: z.string(),
});

export const deleteCourByIdSchema = z.object({
  id: z.string(),
});

export const updateCourInputSchema = z.object({
  id: z.union([z.string(), z.array(z.string())]).optional(),
  name: z.string().optional(),
  images: z.array(z.string()).optional(),
  content: z.string().optional(),
  chapitreId: z.string().optional(),
  description: z.string().optional(),
  isLocked:z.boolean().optional()
  
});
