// Generated by ts-to-zod
import { z } from "zod";
import i18n from "../i18n";

let createMatierSchema: z.ZodType | null;
const checkI18nInitialization = async () => {
  if (!i18n.isInitialized) {
    await new Promise((resolve) => {
      i18n.on("initialized", resolve);
    });
  }
};
const getTranslation = (key: string) => {
  return i18n.t(key);
};
export const validateSubjectInput = async (data: any) => {
  if (!createMatierSchema) {
    await checkI18nInitialization();
    createMatierSchema = await createSubjectInputSchema();
  }
  return createMatierSchema.parse(data);
};
// Regenerate schema when language changes
const handleLanguageChange = async () => {
  createMatierSchema = await createSubjectInputSchema();
};
i18n.on("languageChanged", handleLanguageChange);

export const createSubjectInputSchema = async () => {
  await checkI18nInitialization(); // Ensure i18n is initialized

  return z.object({
    name: z
      .string()
      .min(1, { message: getTranslation("txt_error_name_required") }),
    description: z.string().optional(),
    trimestreId: z
      .string()
      .min(1, {
        message: getTranslation("txt_error_trimester_required"),
      }),
    isLocked: z.boolean().optional(),
  });
};

export const getMatiereByIdSchema = z.object({
  id: z.string(),
});

export const deleteMatiereByIdSchema = z.object({
  id: z.string(),
});

export const updateMatiereByIdSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  trimestreId: z.string(),
  isLocked: z.boolean().optional(),
});
