// Generated by ts-to-zod
import { z } from "zod";

export const createMatiereInputSchema = z.object({
  name: z.string().min(1, { message: "Name is required" }),
  description: z.string().optional(),
  trimestreId: z.string().min(1, { message: "trimester is required" }),
  isLocked: z.boolean().optional(),
});

export const getMatiereByIdSchema = z.object({
  id: z.string(),
});

export const deleteMatiereByIdSchema = z.object({
  id: z.string(),
});

export const updateMatiereByIdSchema = z.object({
  id: z.string().optional(),
  name: z.string().optional(),
  description: z.string().optional(),
  trimestreId: z.string(),
  isLocked: z.boolean().optional(),
});
