// Generated by ts-to-zod
import { z } from "zod";

export const createTrimestreInputSchema = z.object({
  isLocked: z.boolean().optional(), // Optional field, no validation needed
  name: z.string().min(1, { message: "Name is required" }), // Custom error message for name
  slug: z.string().min(1, { message: "Slug is required" }), // Custom error message for slug
  niveauId: z.string().min(1, { message: "Niveau ID is required" }), // Custom error message for niveauId
});

export const getTrimestreByIdSchema = z.object({
  id: z.string(),
});

export const deleteTrimestreByIdSchema = z.object({
  id: z.string(),
});

export const updateTrimestreByIdSchema = z.object({
  id: z.string(),
  name: z.string().optional(),
  slug: z.string().optional(),
});
